### ISSUE TITLE
Undefined reference to `__assert_func` on `-O0` after newlib was removed

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#52]
# Issue
`BN_ASSERT` macro in **`-O0` flag** is broken after 23f4ba2 (newlib removed).
It fails to link with "undefined reference to `__assert_func`".

# Reproduce
Giving linker flag `-O0` in any example should reproduce this.

## Result
building `sprites` example with `-O0`
```
Linking ROM...
.../arm-none-eabi/bin/ld.exe: main.o: in function `bn::degrees_lut_sin(bn::fixed_t<12>)':
/butano/butano/include/bn_math.h:186: undefined reference to `__assert_func'
.../arm-none-eabi/bin/ld.exe: main.o: in function `bn::sprite_rotate_loop_action::sprite_rotate_loop_action(bn::sprite_ptr const&, int, bn::fixed_t<12>)':
/butano/butano/include/bn_sprite_actions.h:617: undefined reference to `__assert_func'
.../arm-none-eabi/bin/ld.exe: main.o: in function `bn::sprite_scale_loop_action::sprite_scale_loop_action(bn::sprite_ptr const&, int, bn::fixed_t<12>)':
/butano/butano/include/bn_sprite_actions.h:1233: undefined reference to `__assert_func'
.../arm-none-eabi/bin/ld.exe: main.o: in function `bn::color::color(int, int, int)':
/butano/butano/include/bn_color.h:55: undefined reference to `__assert_func'
.../arm-none-eabi/bin/ld.exe: /butano/butano/include/bn_color.h:56: undefined reference to `__assert_func'
.../arm-none-eabi/bin/ld.exe: main.o:/butano/butano/include/bn_color.h:57: more undefined references to `__assert_func' follow
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/butano/butano/butano.mak:69: /butano/examples/sprites/sprites.elf] Error 1
make[1]: *** [/butano/butano/butano.mak:202: build] Error 2
make: *** [/butano/butano/butano.mak:197: all] Error 2
```

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/3c2a9cea84a926e2c2ed6d59191c87dadf5acbaf should fix that.

**Comment by copyrat90** [comment]
Yes, it's fixed. Thanks.
